version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: acme-erp-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: acme_erp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d acme_erp" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acme-erp-web
    restart: always
    ports:
      - "8787:8787"
    environment:
      - PORT=8787
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/acme_erp?sslmode=disable
      - BETTER_AUTH_SECRET=ee3e644fc63c3c50d5a15b3ff79057725f35f43698a91f194b34f7ccbff289cd
      - BETTER_AUTH_URL=http://localhost:8787
      - TRUSTED_ORIGINS=http://localhost:5173,http://localhost:3000,http://10.10.10.36:8787,http://10.10.10.30:8787
      - ADMIN_EMAIL=admin@acmehospital.health
      - ADMIN_PASSWORD=AdminAdmin@12345
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "pnpm db:push && pnpm db:seed && exec pnpm start"]

volumes:
  postgres_data:
