/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedCommunicationRouteImport } from './routes/_authenticated/communication'
import { Route as SharedReportTokenRouteImport } from './routes/shared/report/$token'
import { Route as AuthenticatedPurchasesVendorsRouteImport } from './routes/_authenticated/purchases/vendors'
import { Route as AuthenticatedPurchasesUnitTypesRouteImport } from './routes/_authenticated/purchases/unit-types'
import { Route as AuthenticatedPurchasesPurchaseOrdersRouteImport } from './routes/_authenticated/purchases/purchase-orders'
import { Route as AuthenticatedPurchasesItemsRouteImport } from './routes/_authenticated/purchases/items'
import { Route as AuthenticatedPurchasesItemTypesRouteImport } from './routes/_authenticated/purchases/item-types'
import { Route as AuthenticatedPurchasesBillsRouteImport } from './routes/_authenticated/purchases/bills'
import { Route as AuthenticatedMastersShiftsRouteImport } from './routes/_authenticated/masters/shifts'
import { Route as AuthenticatedMastersSalaryTemplatesRouteImport } from './routes/_authenticated/masters/salary-templates'
import { Route as AuthenticatedMastersRolesRouteImport } from './routes/_authenticated/masters/roles'
import { Route as AuthenticatedMastersNursingSupersRouteImport } from './routes/_authenticated/masters/nursing-supers'
import { Route as AuthenticatedMastersManagementApproversRouteImport } from './routes/_authenticated/masters/management-approvers'
import { Route as AuthenticatedMastersLeaveTypesRouteImport } from './routes/_authenticated/masters/leave-types'
import { Route as AuthenticatedMastersDepartmentsRouteImport } from './routes/_authenticated/masters/departments'
import { Route as AuthenticatedMastersBanksRouteImport } from './routes/_authenticated/masters/banks'
import { Route as AuthenticatedHrViewStaffRouteImport } from './routes/_authenticated/hr/view-staff'
import { Route as AuthenticatedHrViewPayslipRouteImport } from './routes/_authenticated/hr/view-payslip'
import { Route as AuthenticatedHrStaffListRouteImport } from './routes/_authenticated/hr/staff-list'
import { Route as AuthenticatedHrRosterRouteImport } from './routes/_authenticated/hr/roster'
import { Route as AuthenticatedHrReviewLeaveRouteImport } from './routes/_authenticated/hr/review-leave'
import { Route as AuthenticatedHrPayrollRouteImport } from './routes/_authenticated/hr/payroll'
import { Route as AuthenticatedHrOffDayRequestsRouteImport } from './routes/_authenticated/hr/off-day-requests'
import { Route as AuthenticatedHrLeavesRouteImport } from './routes/_authenticated/hr/leaves'
import { Route as AuthenticatedHrAttendanceRouteImport } from './routes/_authenticated/hr/attendance'
import { Route as AuthenticatedHrAddStaffRouteImport } from './routes/_authenticated/hr/add-staff'
import { Route as AuthenticatedClinicalImmunizationRouteImport } from './routes/_authenticated/clinical/immunization'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminPayrollRouteImport } from './routes/_authenticated/admin/payroll'
import { Route as AuthenticatedAdminLocalizationRouteImport } from './routes/_authenticated/admin/localization'
import { Route as AuthenticatedAdminHospitalRouteImport } from './routes/_authenticated/admin/hospital'
import { Route as AuthenticatedAccountsServiceChargesRouteImport } from './routes/_authenticated/accounts/service-charges'
import { Route as AuthenticatedAccountsConsultantChargesRouteImport } from './routes/_authenticated/accounts/consultant-charges'
import { Route as AuthenticatedPurchasesPurchaseOrdersIndexRouteImport } from './routes/_authenticated/purchases/purchase-orders/index'
import { Route as AuthenticatedPurchasesGrnsIndexRouteImport } from './routes/_authenticated/purchases/grns/index'
import { Route as AuthenticatedAccountsReportsIndexRouteImport } from './routes/_authenticated/accounts/reports/index'
import { Route as AuthenticatedPurchasesPurchaseOrdersNewRouteImport } from './routes/_authenticated/purchases/purchase-orders/new'
import { Route as AuthenticatedPurchasesPurchaseOrdersIdRouteImport } from './routes/_authenticated/purchases/purchase-orders/$id'
import { Route as AuthenticatedPurchasesGrnsNewRouteImport } from './routes/_authenticated/purchases/grns/new'
import { Route as AuthenticatedPurchasesGrnsGrnIdRouteImport } from './routes/_authenticated/purchases/grns/$grnId'
import { Route as AuthenticatedAccountsReportsNewRouteImport } from './routes/_authenticated/accounts/reports/new'
import { Route as AuthenticatedAccountsReportsIdRouteImport } from './routes/_authenticated/accounts/reports/$id'
import { Route as AuthenticatedPurchasesPurchaseOrdersIdEditRouteImport } from './routes/_authenticated/purchases/purchase-orders/$id_.edit'
import { Route as AuthenticatedPurchasesGrnsGrnIdEditRouteImport } from './routes/_authenticated/purchases/grns/$grnId_.edit'
import { Route as AuthenticatedAccountsReportsEditIdRouteImport } from './routes/_authenticated/accounts/reports/edit.$id'
import { Route as AuthenticatedPurchasesPurchaseOrdersIdGrnNewRouteImport } from './routes/_authenticated/purchases/purchase-orders/$id_.grn.new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunicationRoute =
  AuthenticatedCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const SharedReportTokenRoute = SharedReportTokenRouteImport.update({
  id: '/shared/report/$token',
  path: '/shared/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPurchasesVendorsRoute =
  AuthenticatedPurchasesVendorsRouteImport.update({
    id: '/purchases/vendors',
    path: '/purchases/vendors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesUnitTypesRoute =
  AuthenticatedPurchasesUnitTypesRouteImport.update({
    id: '/purchases/unit-types',
    path: '/purchases/unit-types',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesPurchaseOrdersRoute =
  AuthenticatedPurchasesPurchaseOrdersRouteImport.update({
    id: '/purchases/purchase-orders',
    path: '/purchases/purchase-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesItemsRoute =
  AuthenticatedPurchasesItemsRouteImport.update({
    id: '/purchases/items',
    path: '/purchases/items',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesItemTypesRoute =
  AuthenticatedPurchasesItemTypesRouteImport.update({
    id: '/purchases/item-types',
    path: '/purchases/item-types',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesBillsRoute =
  AuthenticatedPurchasesBillsRouteImport.update({
    id: '/purchases/bills',
    path: '/purchases/bills',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersShiftsRoute =
  AuthenticatedMastersShiftsRouteImport.update({
    id: '/masters/shifts',
    path: '/masters/shifts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersSalaryTemplatesRoute =
  AuthenticatedMastersSalaryTemplatesRouteImport.update({
    id: '/masters/salary-templates',
    path: '/masters/salary-templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersRolesRoute =
  AuthenticatedMastersRolesRouteImport.update({
    id: '/masters/roles',
    path: '/masters/roles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersNursingSupersRoute =
  AuthenticatedMastersNursingSupersRouteImport.update({
    id: '/masters/nursing-supers',
    path: '/masters/nursing-supers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersManagementApproversRoute =
  AuthenticatedMastersManagementApproversRouteImport.update({
    id: '/masters/management-approvers',
    path: '/masters/management-approvers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersLeaveTypesRoute =
  AuthenticatedMastersLeaveTypesRouteImport.update({
    id: '/masters/leave-types',
    path: '/masters/leave-types',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersDepartmentsRoute =
  AuthenticatedMastersDepartmentsRouteImport.update({
    id: '/masters/departments',
    path: '/masters/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersBanksRoute =
  AuthenticatedMastersBanksRouteImport.update({
    id: '/masters/banks',
    path: '/masters/banks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrViewStaffRoute =
  AuthenticatedHrViewStaffRouteImport.update({
    id: '/hr/view-staff',
    path: '/hr/view-staff',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrViewPayslipRoute =
  AuthenticatedHrViewPayslipRouteImport.update({
    id: '/hr/view-payslip',
    path: '/hr/view-payslip',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrStaffListRoute =
  AuthenticatedHrStaffListRouteImport.update({
    id: '/hr/staff-list',
    path: '/hr/staff-list',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrRosterRoute = AuthenticatedHrRosterRouteImport.update({
  id: '/hr/roster',
  path: '/hr/roster',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrReviewLeaveRoute =
  AuthenticatedHrReviewLeaveRouteImport.update({
    id: '/hr/review-leave',
    path: '/hr/review-leave',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrPayrollRoute = AuthenticatedHrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrOffDayRequestsRoute =
  AuthenticatedHrOffDayRequestsRouteImport.update({
    id: '/hr/off-day-requests',
    path: '/hr/off-day-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrLeavesRoute = AuthenticatedHrLeavesRouteImport.update({
  id: '/hr/leaves',
  path: '/hr/leaves',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrAttendanceRoute =
  AuthenticatedHrAttendanceRouteImport.update({
    id: '/hr/attendance',
    path: '/hr/attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrAddStaffRoute = AuthenticatedHrAddStaffRouteImport.update({
  id: '/hr/add-staff',
  path: '/hr/add-staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClinicalImmunizationRoute =
  AuthenticatedClinicalImmunizationRouteImport.update({
    id: '/clinical/immunization',
    path: '/clinical/immunization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPayrollRoute =
  AuthenticatedAdminPayrollRouteImport.update({
    id: '/admin/payroll',
    path: '/admin/payroll',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLocalizationRoute =
  AuthenticatedAdminLocalizationRouteImport.update({
    id: '/admin/localization',
    path: '/admin/localization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminHospitalRoute =
  AuthenticatedAdminHospitalRouteImport.update({
    id: '/admin/hospital',
    path: '/admin/hospital',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsServiceChargesRoute =
  AuthenticatedAccountsServiceChargesRouteImport.update({
    id: '/accounts/service-charges',
    path: '/accounts/service-charges',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsConsultantChargesRoute =
  AuthenticatedAccountsConsultantChargesRouteImport.update({
    id: '/accounts/consultant-charges',
    path: '/accounts/consultant-charges',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesPurchaseOrdersIndexRoute =
  AuthenticatedPurchasesPurchaseOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPurchasesPurchaseOrdersRoute,
  } as any)
const AuthenticatedPurchasesGrnsIndexRoute =
  AuthenticatedPurchasesGrnsIndexRouteImport.update({
    id: '/purchases/grns/',
    path: '/purchases/grns/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsReportsIndexRoute =
  AuthenticatedAccountsReportsIndexRouteImport.update({
    id: '/accounts/reports/',
    path: '/accounts/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesPurchaseOrdersNewRoute =
  AuthenticatedPurchasesPurchaseOrdersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPurchasesPurchaseOrdersRoute,
  } as any)
const AuthenticatedPurchasesPurchaseOrdersIdRoute =
  AuthenticatedPurchasesPurchaseOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPurchasesPurchaseOrdersRoute,
  } as any)
const AuthenticatedPurchasesGrnsNewRoute =
  AuthenticatedPurchasesGrnsNewRouteImport.update({
    id: '/purchases/grns/new',
    path: '/purchases/grns/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesGrnsGrnIdRoute =
  AuthenticatedPurchasesGrnsGrnIdRouteImport.update({
    id: '/purchases/grns/$grnId',
    path: '/purchases/grns/$grnId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsReportsNewRoute =
  AuthenticatedAccountsReportsNewRouteImport.update({
    id: '/accounts/reports/new',
    path: '/accounts/reports/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsReportsIdRoute =
  AuthenticatedAccountsReportsIdRouteImport.update({
    id: '/accounts/reports/$id',
    path: '/accounts/reports/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesPurchaseOrdersIdEditRoute =
  AuthenticatedPurchasesPurchaseOrdersIdEditRouteImport.update({
    id: '/$id_/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedPurchasesPurchaseOrdersRoute,
  } as any)
const AuthenticatedPurchasesGrnsGrnIdEditRoute =
  AuthenticatedPurchasesGrnsGrnIdEditRouteImport.update({
    id: '/purchases/grns/$grnId_/edit',
    path: '/purchases/grns/$grnId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsReportsEditIdRoute =
  AuthenticatedAccountsReportsEditIdRouteImport.update({
    id: '/accounts/reports/edit/$id',
    path: '/accounts/reports/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesPurchaseOrdersIdGrnNewRoute =
  AuthenticatedPurchasesPurchaseOrdersIdGrnNewRouteImport.update({
    id: '/$id_/grn/new',
    path: '/$id/grn/new',
    getParentRoute: () => AuthenticatedPurchasesPurchaseOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/accounts/consultant-charges': typeof AuthenticatedAccountsConsultantChargesRoute
  '/accounts/service-charges': typeof AuthenticatedAccountsServiceChargesRoute
  '/admin/hospital': typeof AuthenticatedAdminHospitalRoute
  '/admin/localization': typeof AuthenticatedAdminLocalizationRoute
  '/admin/payroll': typeof AuthenticatedAdminPayrollRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/clinical/immunization': typeof AuthenticatedClinicalImmunizationRoute
  '/hr/add-staff': typeof AuthenticatedHrAddStaffRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/leaves': typeof AuthenticatedHrLeavesRoute
  '/hr/off-day-requests': typeof AuthenticatedHrOffDayRequestsRoute
  '/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/hr/review-leave': typeof AuthenticatedHrReviewLeaveRoute
  '/hr/roster': typeof AuthenticatedHrRosterRoute
  '/hr/staff-list': typeof AuthenticatedHrStaffListRoute
  '/hr/view-payslip': typeof AuthenticatedHrViewPayslipRoute
  '/hr/view-staff': typeof AuthenticatedHrViewStaffRoute
  '/masters/banks': typeof AuthenticatedMastersBanksRoute
  '/masters/departments': typeof AuthenticatedMastersDepartmentsRoute
  '/masters/leave-types': typeof AuthenticatedMastersLeaveTypesRoute
  '/masters/management-approvers': typeof AuthenticatedMastersManagementApproversRoute
  '/masters/nursing-supers': typeof AuthenticatedMastersNursingSupersRoute
  '/masters/roles': typeof AuthenticatedMastersRolesRoute
  '/masters/salary-templates': typeof AuthenticatedMastersSalaryTemplatesRoute
  '/masters/shifts': typeof AuthenticatedMastersShiftsRoute
  '/purchases/bills': typeof AuthenticatedPurchasesBillsRoute
  '/purchases/item-types': typeof AuthenticatedPurchasesItemTypesRoute
  '/purchases/items': typeof AuthenticatedPurchasesItemsRoute
  '/purchases/purchase-orders': typeof AuthenticatedPurchasesPurchaseOrdersRouteWithChildren
  '/purchases/unit-types': typeof AuthenticatedPurchasesUnitTypesRoute
  '/purchases/vendors': typeof AuthenticatedPurchasesVendorsRoute
  '/shared/report/$token': typeof SharedReportTokenRoute
  '/accounts/reports/$id': typeof AuthenticatedAccountsReportsIdRoute
  '/accounts/reports/new': typeof AuthenticatedAccountsReportsNewRoute
  '/purchases/grns/$grnId': typeof AuthenticatedPurchasesGrnsGrnIdRoute
  '/purchases/grns/new': typeof AuthenticatedPurchasesGrnsNewRoute
  '/purchases/purchase-orders/$id': typeof AuthenticatedPurchasesPurchaseOrdersIdRoute
  '/purchases/purchase-orders/new': typeof AuthenticatedPurchasesPurchaseOrdersNewRoute
  '/accounts/reports/': typeof AuthenticatedAccountsReportsIndexRoute
  '/purchases/grns/': typeof AuthenticatedPurchasesGrnsIndexRoute
  '/purchases/purchase-orders/': typeof AuthenticatedPurchasesPurchaseOrdersIndexRoute
  '/accounts/reports/edit/$id': typeof AuthenticatedAccountsReportsEditIdRoute
  '/purchases/grns/$grnId/edit': typeof AuthenticatedPurchasesGrnsGrnIdEditRoute
  '/purchases/purchase-orders/$id/edit': typeof AuthenticatedPurchasesPurchaseOrdersIdEditRoute
  '/purchases/purchase-orders/$id/grn/new': typeof AuthenticatedPurchasesPurchaseOrdersIdGrnNewRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/accounts/consultant-charges': typeof AuthenticatedAccountsConsultantChargesRoute
  '/accounts/service-charges': typeof AuthenticatedAccountsServiceChargesRoute
  '/admin/hospital': typeof AuthenticatedAdminHospitalRoute
  '/admin/localization': typeof AuthenticatedAdminLocalizationRoute
  '/admin/payroll': typeof AuthenticatedAdminPayrollRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/clinical/immunization': typeof AuthenticatedClinicalImmunizationRoute
  '/hr/add-staff': typeof AuthenticatedHrAddStaffRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/leaves': typeof AuthenticatedHrLeavesRoute
  '/hr/off-day-requests': typeof AuthenticatedHrOffDayRequestsRoute
  '/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/hr/review-leave': typeof AuthenticatedHrReviewLeaveRoute
  '/hr/roster': typeof AuthenticatedHrRosterRoute
  '/hr/staff-list': typeof AuthenticatedHrStaffListRoute
  '/hr/view-payslip': typeof AuthenticatedHrViewPayslipRoute
  '/hr/view-staff': typeof AuthenticatedHrViewStaffRoute
  '/masters/banks': typeof AuthenticatedMastersBanksRoute
  '/masters/departments': typeof AuthenticatedMastersDepartmentsRoute
  '/masters/leave-types': typeof AuthenticatedMastersLeaveTypesRoute
  '/masters/management-approvers': typeof AuthenticatedMastersManagementApproversRoute
  '/masters/nursing-supers': typeof AuthenticatedMastersNursingSupersRoute
  '/masters/roles': typeof AuthenticatedMastersRolesRoute
  '/masters/salary-templates': typeof AuthenticatedMastersSalaryTemplatesRoute
  '/masters/shifts': typeof AuthenticatedMastersShiftsRoute
  '/purchases/bills': typeof AuthenticatedPurchasesBillsRoute
  '/purchases/item-types': typeof AuthenticatedPurchasesItemTypesRoute
  '/purchases/items': typeof AuthenticatedPurchasesItemsRoute
  '/purchases/unit-types': typeof AuthenticatedPurchasesUnitTypesRoute
  '/purchases/vendors': typeof AuthenticatedPurchasesVendorsRoute
  '/shared/report/$token': typeof SharedReportTokenRoute
  '/accounts/reports/$id': typeof AuthenticatedAccountsReportsIdRoute
  '/accounts/reports/new': typeof AuthenticatedAccountsReportsNewRoute
  '/purchases/grns/$grnId': typeof AuthenticatedPurchasesGrnsGrnIdRoute
  '/purchases/grns/new': typeof AuthenticatedPurchasesGrnsNewRoute
  '/purchases/purchase-orders/$id': typeof AuthenticatedPurchasesPurchaseOrdersIdRoute
  '/purchases/purchase-orders/new': typeof AuthenticatedPurchasesPurchaseOrdersNewRoute
  '/accounts/reports': typeof AuthenticatedAccountsReportsIndexRoute
  '/purchases/grns': typeof AuthenticatedPurchasesGrnsIndexRoute
  '/purchases/purchase-orders': typeof AuthenticatedPurchasesPurchaseOrdersIndexRoute
  '/accounts/reports/edit/$id': typeof AuthenticatedAccountsReportsEditIdRoute
  '/purchases/grns/$grnId/edit': typeof AuthenticatedPurchasesGrnsGrnIdEditRoute
  '/purchases/purchase-orders/$id/edit': typeof AuthenticatedPurchasesPurchaseOrdersIdEditRoute
  '/purchases/purchase-orders/$id/grn/new': typeof AuthenticatedPurchasesPurchaseOrdersIdGrnNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/_authenticated/communication': typeof AuthenticatedCommunicationRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/accounts/consultant-charges': typeof AuthenticatedAccountsConsultantChargesRoute
  '/_authenticated/accounts/service-charges': typeof AuthenticatedAccountsServiceChargesRoute
  '/_authenticated/admin/hospital': typeof AuthenticatedAdminHospitalRoute
  '/_authenticated/admin/localization': typeof AuthenticatedAdminLocalizationRoute
  '/_authenticated/admin/payroll': typeof AuthenticatedAdminPayrollRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/clinical/immunization': typeof AuthenticatedClinicalImmunizationRoute
  '/_authenticated/hr/add-staff': typeof AuthenticatedHrAddStaffRoute
  '/_authenticated/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/_authenticated/hr/leaves': typeof AuthenticatedHrLeavesRoute
  '/_authenticated/hr/off-day-requests': typeof AuthenticatedHrOffDayRequestsRoute
  '/_authenticated/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/_authenticated/hr/review-leave': typeof AuthenticatedHrReviewLeaveRoute
  '/_authenticated/hr/roster': typeof AuthenticatedHrRosterRoute
  '/_authenticated/hr/staff-list': typeof AuthenticatedHrStaffListRoute
  '/_authenticated/hr/view-payslip': typeof AuthenticatedHrViewPayslipRoute
  '/_authenticated/hr/view-staff': typeof AuthenticatedHrViewStaffRoute
  '/_authenticated/masters/banks': typeof AuthenticatedMastersBanksRoute
  '/_authenticated/masters/departments': typeof AuthenticatedMastersDepartmentsRoute
  '/_authenticated/masters/leave-types': typeof AuthenticatedMastersLeaveTypesRoute
  '/_authenticated/masters/management-approvers': typeof AuthenticatedMastersManagementApproversRoute
  '/_authenticated/masters/nursing-supers': typeof AuthenticatedMastersNursingSupersRoute
  '/_authenticated/masters/roles': typeof AuthenticatedMastersRolesRoute
  '/_authenticated/masters/salary-templates': typeof AuthenticatedMastersSalaryTemplatesRoute
  '/_authenticated/masters/shifts': typeof AuthenticatedMastersShiftsRoute
  '/_authenticated/purchases/bills': typeof AuthenticatedPurchasesBillsRoute
  '/_authenticated/purchases/item-types': typeof AuthenticatedPurchasesItemTypesRoute
  '/_authenticated/purchases/items': typeof AuthenticatedPurchasesItemsRoute
  '/_authenticated/purchases/purchase-orders': typeof AuthenticatedPurchasesPurchaseOrdersRouteWithChildren
  '/_authenticated/purchases/unit-types': typeof AuthenticatedPurchasesUnitTypesRoute
  '/_authenticated/purchases/vendors': typeof AuthenticatedPurchasesVendorsRoute
  '/shared/report/$token': typeof SharedReportTokenRoute
  '/_authenticated/accounts/reports/$id': typeof AuthenticatedAccountsReportsIdRoute
  '/_authenticated/accounts/reports/new': typeof AuthenticatedAccountsReportsNewRoute
  '/_authenticated/purchases/grns/$grnId': typeof AuthenticatedPurchasesGrnsGrnIdRoute
  '/_authenticated/purchases/grns/new': typeof AuthenticatedPurchasesGrnsNewRoute
  '/_authenticated/purchases/purchase-orders/$id': typeof AuthenticatedPurchasesPurchaseOrdersIdRoute
  '/_authenticated/purchases/purchase-orders/new': typeof AuthenticatedPurchasesPurchaseOrdersNewRoute
  '/_authenticated/accounts/reports/': typeof AuthenticatedAccountsReportsIndexRoute
  '/_authenticated/purchases/grns/': typeof AuthenticatedPurchasesGrnsIndexRoute
  '/_authenticated/purchases/purchase-orders/': typeof AuthenticatedPurchasesPurchaseOrdersIndexRoute
  '/_authenticated/accounts/reports/edit/$id': typeof AuthenticatedAccountsReportsEditIdRoute
  '/_authenticated/purchases/grns/$grnId_/edit': typeof AuthenticatedPurchasesGrnsGrnIdEditRoute
  '/_authenticated/purchases/purchase-orders/$id_/edit': typeof AuthenticatedPurchasesPurchaseOrdersIdEditRoute
  '/_authenticated/purchases/purchase-orders/$id_/grn/new': typeof AuthenticatedPurchasesPurchaseOrdersIdGrnNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/communication'
    | '/settings'
    | '/accounts/consultant-charges'
    | '/accounts/service-charges'
    | '/admin/hospital'
    | '/admin/localization'
    | '/admin/payroll'
    | '/admin/users'
    | '/clinical/immunization'
    | '/hr/add-staff'
    | '/hr/attendance'
    | '/hr/leaves'
    | '/hr/off-day-requests'
    | '/hr/payroll'
    | '/hr/review-leave'
    | '/hr/roster'
    | '/hr/staff-list'
    | '/hr/view-payslip'
    | '/hr/view-staff'
    | '/masters/banks'
    | '/masters/departments'
    | '/masters/leave-types'
    | '/masters/management-approvers'
    | '/masters/nursing-supers'
    | '/masters/roles'
    | '/masters/salary-templates'
    | '/masters/shifts'
    | '/purchases/bills'
    | '/purchases/item-types'
    | '/purchases/items'
    | '/purchases/purchase-orders'
    | '/purchases/unit-types'
    | '/purchases/vendors'
    | '/shared/report/$token'
    | '/accounts/reports/$id'
    | '/accounts/reports/new'
    | '/purchases/grns/$grnId'
    | '/purchases/grns/new'
    | '/purchases/purchase-orders/$id'
    | '/purchases/purchase-orders/new'
    | '/accounts/reports/'
    | '/purchases/grns/'
    | '/purchases/purchase-orders/'
    | '/accounts/reports/edit/$id'
    | '/purchases/grns/$grnId/edit'
    | '/purchases/purchase-orders/$id/edit'
    | '/purchases/purchase-orders/$id/grn/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/login'
    | '/communication'
    | '/settings'
    | '/'
    | '/accounts/consultant-charges'
    | '/accounts/service-charges'
    | '/admin/hospital'
    | '/admin/localization'
    | '/admin/payroll'
    | '/admin/users'
    | '/clinical/immunization'
    | '/hr/add-staff'
    | '/hr/attendance'
    | '/hr/leaves'
    | '/hr/off-day-requests'
    | '/hr/payroll'
    | '/hr/review-leave'
    | '/hr/roster'
    | '/hr/staff-list'
    | '/hr/view-payslip'
    | '/hr/view-staff'
    | '/masters/banks'
    | '/masters/departments'
    | '/masters/leave-types'
    | '/masters/management-approvers'
    | '/masters/nursing-supers'
    | '/masters/roles'
    | '/masters/salary-templates'
    | '/masters/shifts'
    | '/purchases/bills'
    | '/purchases/item-types'
    | '/purchases/items'
    | '/purchases/unit-types'
    | '/purchases/vendors'
    | '/shared/report/$token'
    | '/accounts/reports/$id'
    | '/accounts/reports/new'
    | '/purchases/grns/$grnId'
    | '/purchases/grns/new'
    | '/purchases/purchase-orders/$id'
    | '/purchases/purchase-orders/new'
    | '/accounts/reports'
    | '/purchases/grns'
    | '/purchases/purchase-orders'
    | '/accounts/reports/edit/$id'
    | '/purchases/grns/$grnId/edit'
    | '/purchases/purchase-orders/$id/edit'
    | '/purchases/purchase-orders/$id/grn/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/change-password'
    | '/login'
    | '/_authenticated/communication'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/accounts/consultant-charges'
    | '/_authenticated/accounts/service-charges'
    | '/_authenticated/admin/hospital'
    | '/_authenticated/admin/localization'
    | '/_authenticated/admin/payroll'
    | '/_authenticated/admin/users'
    | '/_authenticated/clinical/immunization'
    | '/_authenticated/hr/add-staff'
    | '/_authenticated/hr/attendance'
    | '/_authenticated/hr/leaves'
    | '/_authenticated/hr/off-day-requests'
    | '/_authenticated/hr/payroll'
    | '/_authenticated/hr/review-leave'
    | '/_authenticated/hr/roster'
    | '/_authenticated/hr/staff-list'
    | '/_authenticated/hr/view-payslip'
    | '/_authenticated/hr/view-staff'
    | '/_authenticated/masters/banks'
    | '/_authenticated/masters/departments'
    | '/_authenticated/masters/leave-types'
    | '/_authenticated/masters/management-approvers'
    | '/_authenticated/masters/nursing-supers'
    | '/_authenticated/masters/roles'
    | '/_authenticated/masters/salary-templates'
    | '/_authenticated/masters/shifts'
    | '/_authenticated/purchases/bills'
    | '/_authenticated/purchases/item-types'
    | '/_authenticated/purchases/items'
    | '/_authenticated/purchases/purchase-orders'
    | '/_authenticated/purchases/unit-types'
    | '/_authenticated/purchases/vendors'
    | '/shared/report/$token'
    | '/_authenticated/accounts/reports/$id'
    | '/_authenticated/accounts/reports/new'
    | '/_authenticated/purchases/grns/$grnId'
    | '/_authenticated/purchases/grns/new'
    | '/_authenticated/purchases/purchase-orders/$id'
    | '/_authenticated/purchases/purchase-orders/new'
    | '/_authenticated/accounts/reports/'
    | '/_authenticated/purchases/grns/'
    | '/_authenticated/purchases/purchase-orders/'
    | '/_authenticated/accounts/reports/edit/$id'
    | '/_authenticated/purchases/grns/$grnId_/edit'
    | '/_authenticated/purchases/purchase-orders/$id_/edit'
    | '/_authenticated/purchases/purchase-orders/$id_/grn/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  SharedReportTokenRoute: typeof SharedReportTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/communication': {
      id: '/_authenticated/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof AuthenticatedCommunicationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/shared/report/$token': {
      id: '/shared/report/$token'
      path: '/shared/report/$token'
      fullPath: '/shared/report/$token'
      preLoaderRoute: typeof SharedReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/purchases/vendors': {
      id: '/_authenticated/purchases/vendors'
      path: '/purchases/vendors'
      fullPath: '/purchases/vendors'
      preLoaderRoute: typeof AuthenticatedPurchasesVendorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/unit-types': {
      id: '/_authenticated/purchases/unit-types'
      path: '/purchases/unit-types'
      fullPath: '/purchases/unit-types'
      preLoaderRoute: typeof AuthenticatedPurchasesUnitTypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/purchase-orders': {
      id: '/_authenticated/purchases/purchase-orders'
      path: '/purchases/purchase-orders'
      fullPath: '/purchases/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchasesPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/items': {
      id: '/_authenticated/purchases/items'
      path: '/purchases/items'
      fullPath: '/purchases/items'
      preLoaderRoute: typeof AuthenticatedPurchasesItemsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/item-types': {
      id: '/_authenticated/purchases/item-types'
      path: '/purchases/item-types'
      fullPath: '/purchases/item-types'
      preLoaderRoute: typeof AuthenticatedPurchasesItemTypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/bills': {
      id: '/_authenticated/purchases/bills'
      path: '/purchases/bills'
      fullPath: '/purchases/bills'
      preLoaderRoute: typeof AuthenticatedPurchasesBillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/shifts': {
      id: '/_authenticated/masters/shifts'
      path: '/masters/shifts'
      fullPath: '/masters/shifts'
      preLoaderRoute: typeof AuthenticatedMastersShiftsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/salary-templates': {
      id: '/_authenticated/masters/salary-templates'
      path: '/masters/salary-templates'
      fullPath: '/masters/salary-templates'
      preLoaderRoute: typeof AuthenticatedMastersSalaryTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/roles': {
      id: '/_authenticated/masters/roles'
      path: '/masters/roles'
      fullPath: '/masters/roles'
      preLoaderRoute: typeof AuthenticatedMastersRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/nursing-supers': {
      id: '/_authenticated/masters/nursing-supers'
      path: '/masters/nursing-supers'
      fullPath: '/masters/nursing-supers'
      preLoaderRoute: typeof AuthenticatedMastersNursingSupersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/management-approvers': {
      id: '/_authenticated/masters/management-approvers'
      path: '/masters/management-approvers'
      fullPath: '/masters/management-approvers'
      preLoaderRoute: typeof AuthenticatedMastersManagementApproversRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/leave-types': {
      id: '/_authenticated/masters/leave-types'
      path: '/masters/leave-types'
      fullPath: '/masters/leave-types'
      preLoaderRoute: typeof AuthenticatedMastersLeaveTypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/departments': {
      id: '/_authenticated/masters/departments'
      path: '/masters/departments'
      fullPath: '/masters/departments'
      preLoaderRoute: typeof AuthenticatedMastersDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/banks': {
      id: '/_authenticated/masters/banks'
      path: '/masters/banks'
      fullPath: '/masters/banks'
      preLoaderRoute: typeof AuthenticatedMastersBanksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/view-staff': {
      id: '/_authenticated/hr/view-staff'
      path: '/hr/view-staff'
      fullPath: '/hr/view-staff'
      preLoaderRoute: typeof AuthenticatedHrViewStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/view-payslip': {
      id: '/_authenticated/hr/view-payslip'
      path: '/hr/view-payslip'
      fullPath: '/hr/view-payslip'
      preLoaderRoute: typeof AuthenticatedHrViewPayslipRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/staff-list': {
      id: '/_authenticated/hr/staff-list'
      path: '/hr/staff-list'
      fullPath: '/hr/staff-list'
      preLoaderRoute: typeof AuthenticatedHrStaffListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/roster': {
      id: '/_authenticated/hr/roster'
      path: '/hr/roster'
      fullPath: '/hr/roster'
      preLoaderRoute: typeof AuthenticatedHrRosterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/review-leave': {
      id: '/_authenticated/hr/review-leave'
      path: '/hr/review-leave'
      fullPath: '/hr/review-leave'
      preLoaderRoute: typeof AuthenticatedHrReviewLeaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/payroll': {
      id: '/_authenticated/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof AuthenticatedHrPayrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/off-day-requests': {
      id: '/_authenticated/hr/off-day-requests'
      path: '/hr/off-day-requests'
      fullPath: '/hr/off-day-requests'
      preLoaderRoute: typeof AuthenticatedHrOffDayRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/leaves': {
      id: '/_authenticated/hr/leaves'
      path: '/hr/leaves'
      fullPath: '/hr/leaves'
      preLoaderRoute: typeof AuthenticatedHrLeavesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/attendance': {
      id: '/_authenticated/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof AuthenticatedHrAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/add-staff': {
      id: '/_authenticated/hr/add-staff'
      path: '/hr/add-staff'
      fullPath: '/hr/add-staff'
      preLoaderRoute: typeof AuthenticatedHrAddStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clinical/immunization': {
      id: '/_authenticated/clinical/immunization'
      path: '/clinical/immunization'
      fullPath: '/clinical/immunization'
      preLoaderRoute: typeof AuthenticatedClinicalImmunizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/payroll': {
      id: '/_authenticated/admin/payroll'
      path: '/admin/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AuthenticatedAdminPayrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/localization': {
      id: '/_authenticated/admin/localization'
      path: '/admin/localization'
      fullPath: '/admin/localization'
      preLoaderRoute: typeof AuthenticatedAdminLocalizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/hospital': {
      id: '/_authenticated/admin/hospital'
      path: '/admin/hospital'
      fullPath: '/admin/hospital'
      preLoaderRoute: typeof AuthenticatedAdminHospitalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/service-charges': {
      id: '/_authenticated/accounts/service-charges'
      path: '/accounts/service-charges'
      fullPath: '/accounts/service-charges'
      preLoaderRoute: typeof AuthenticatedAccountsServiceChargesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/consultant-charges': {
      id: '/_authenticated/accounts/consultant-charges'
      path: '/accounts/consultant-charges'
      fullPath: '/accounts/consultant-charges'
      preLoaderRoute: typeof AuthenticatedAccountsConsultantChargesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/purchase-orders/': {
      id: '/_authenticated/purchases/purchase-orders/'
      path: '/'
      fullPath: '/purchases/purchase-orders/'
      preLoaderRoute: typeof AuthenticatedPurchasesPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedPurchasesPurchaseOrdersRoute
    }
    '/_authenticated/purchases/grns/': {
      id: '/_authenticated/purchases/grns/'
      path: '/purchases/grns'
      fullPath: '/purchases/grns/'
      preLoaderRoute: typeof AuthenticatedPurchasesGrnsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/reports/': {
      id: '/_authenticated/accounts/reports/'
      path: '/accounts/reports'
      fullPath: '/accounts/reports/'
      preLoaderRoute: typeof AuthenticatedAccountsReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/purchase-orders/new': {
      id: '/_authenticated/purchases/purchase-orders/new'
      path: '/new'
      fullPath: '/purchases/purchase-orders/new'
      preLoaderRoute: typeof AuthenticatedPurchasesPurchaseOrdersNewRouteImport
      parentRoute: typeof AuthenticatedPurchasesPurchaseOrdersRoute
    }
    '/_authenticated/purchases/purchase-orders/$id': {
      id: '/_authenticated/purchases/purchase-orders/$id'
      path: '/$id'
      fullPath: '/purchases/purchase-orders/$id'
      preLoaderRoute: typeof AuthenticatedPurchasesPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthenticatedPurchasesPurchaseOrdersRoute
    }
    '/_authenticated/purchases/grns/new': {
      id: '/_authenticated/purchases/grns/new'
      path: '/purchases/grns/new'
      fullPath: '/purchases/grns/new'
      preLoaderRoute: typeof AuthenticatedPurchasesGrnsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/grns/$grnId': {
      id: '/_authenticated/purchases/grns/$grnId'
      path: '/purchases/grns/$grnId'
      fullPath: '/purchases/grns/$grnId'
      preLoaderRoute: typeof AuthenticatedPurchasesGrnsGrnIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/reports/new': {
      id: '/_authenticated/accounts/reports/new'
      path: '/accounts/reports/new'
      fullPath: '/accounts/reports/new'
      preLoaderRoute: typeof AuthenticatedAccountsReportsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/reports/$id': {
      id: '/_authenticated/accounts/reports/$id'
      path: '/accounts/reports/$id'
      fullPath: '/accounts/reports/$id'
      preLoaderRoute: typeof AuthenticatedAccountsReportsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/purchase-orders/$id_/edit': {
      id: '/_authenticated/purchases/purchase-orders/$id_/edit'
      path: '/$id/edit'
      fullPath: '/purchases/purchase-orders/$id/edit'
      preLoaderRoute: typeof AuthenticatedPurchasesPurchaseOrdersIdEditRouteImport
      parentRoute: typeof AuthenticatedPurchasesPurchaseOrdersRoute
    }
    '/_authenticated/purchases/grns/$grnId_/edit': {
      id: '/_authenticated/purchases/grns/$grnId_/edit'
      path: '/purchases/grns/$grnId/edit'
      fullPath: '/purchases/grns/$grnId/edit'
      preLoaderRoute: typeof AuthenticatedPurchasesGrnsGrnIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/reports/edit/$id': {
      id: '/_authenticated/accounts/reports/edit/$id'
      path: '/accounts/reports/edit/$id'
      fullPath: '/accounts/reports/edit/$id'
      preLoaderRoute: typeof AuthenticatedAccountsReportsEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/purchase-orders/$id_/grn/new': {
      id: '/_authenticated/purchases/purchase-orders/$id_/grn/new'
      path: '/$id/grn/new'
      fullPath: '/purchases/purchase-orders/$id/grn/new'
      preLoaderRoute: typeof AuthenticatedPurchasesPurchaseOrdersIdGrnNewRouteImport
      parentRoute: typeof AuthenticatedPurchasesPurchaseOrdersRoute
    }
  }
}

interface AuthenticatedPurchasesPurchaseOrdersRouteChildren {
  AuthenticatedPurchasesPurchaseOrdersIdRoute: typeof AuthenticatedPurchasesPurchaseOrdersIdRoute
  AuthenticatedPurchasesPurchaseOrdersNewRoute: typeof AuthenticatedPurchasesPurchaseOrdersNewRoute
  AuthenticatedPurchasesPurchaseOrdersIndexRoute: typeof AuthenticatedPurchasesPurchaseOrdersIndexRoute
  AuthenticatedPurchasesPurchaseOrdersIdEditRoute: typeof AuthenticatedPurchasesPurchaseOrdersIdEditRoute
  AuthenticatedPurchasesPurchaseOrdersIdGrnNewRoute: typeof AuthenticatedPurchasesPurchaseOrdersIdGrnNewRoute
}

const AuthenticatedPurchasesPurchaseOrdersRouteChildren: AuthenticatedPurchasesPurchaseOrdersRouteChildren =
  {
    AuthenticatedPurchasesPurchaseOrdersIdRoute:
      AuthenticatedPurchasesPurchaseOrdersIdRoute,
    AuthenticatedPurchasesPurchaseOrdersNewRoute:
      AuthenticatedPurchasesPurchaseOrdersNewRoute,
    AuthenticatedPurchasesPurchaseOrdersIndexRoute:
      AuthenticatedPurchasesPurchaseOrdersIndexRoute,
    AuthenticatedPurchasesPurchaseOrdersIdEditRoute:
      AuthenticatedPurchasesPurchaseOrdersIdEditRoute,
    AuthenticatedPurchasesPurchaseOrdersIdGrnNewRoute:
      AuthenticatedPurchasesPurchaseOrdersIdGrnNewRoute,
  }

const AuthenticatedPurchasesPurchaseOrdersRouteWithChildren =
  AuthenticatedPurchasesPurchaseOrdersRoute._addFileChildren(
    AuthenticatedPurchasesPurchaseOrdersRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCommunicationRoute: typeof AuthenticatedCommunicationRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccountsConsultantChargesRoute: typeof AuthenticatedAccountsConsultantChargesRoute
  AuthenticatedAccountsServiceChargesRoute: typeof AuthenticatedAccountsServiceChargesRoute
  AuthenticatedAdminHospitalRoute: typeof AuthenticatedAdminHospitalRoute
  AuthenticatedAdminLocalizationRoute: typeof AuthenticatedAdminLocalizationRoute
  AuthenticatedAdminPayrollRoute: typeof AuthenticatedAdminPayrollRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedClinicalImmunizationRoute: typeof AuthenticatedClinicalImmunizationRoute
  AuthenticatedHrAddStaffRoute: typeof AuthenticatedHrAddStaffRoute
  AuthenticatedHrAttendanceRoute: typeof AuthenticatedHrAttendanceRoute
  AuthenticatedHrLeavesRoute: typeof AuthenticatedHrLeavesRoute
  AuthenticatedHrOffDayRequestsRoute: typeof AuthenticatedHrOffDayRequestsRoute
  AuthenticatedHrPayrollRoute: typeof AuthenticatedHrPayrollRoute
  AuthenticatedHrReviewLeaveRoute: typeof AuthenticatedHrReviewLeaveRoute
  AuthenticatedHrRosterRoute: typeof AuthenticatedHrRosterRoute
  AuthenticatedHrStaffListRoute: typeof AuthenticatedHrStaffListRoute
  AuthenticatedHrViewPayslipRoute: typeof AuthenticatedHrViewPayslipRoute
  AuthenticatedHrViewStaffRoute: typeof AuthenticatedHrViewStaffRoute
  AuthenticatedMastersBanksRoute: typeof AuthenticatedMastersBanksRoute
  AuthenticatedMastersDepartmentsRoute: typeof AuthenticatedMastersDepartmentsRoute
  AuthenticatedMastersLeaveTypesRoute: typeof AuthenticatedMastersLeaveTypesRoute
  AuthenticatedMastersManagementApproversRoute: typeof AuthenticatedMastersManagementApproversRoute
  AuthenticatedMastersNursingSupersRoute: typeof AuthenticatedMastersNursingSupersRoute
  AuthenticatedMastersRolesRoute: typeof AuthenticatedMastersRolesRoute
  AuthenticatedMastersSalaryTemplatesRoute: typeof AuthenticatedMastersSalaryTemplatesRoute
  AuthenticatedMastersShiftsRoute: typeof AuthenticatedMastersShiftsRoute
  AuthenticatedPurchasesBillsRoute: typeof AuthenticatedPurchasesBillsRoute
  AuthenticatedPurchasesItemTypesRoute: typeof AuthenticatedPurchasesItemTypesRoute
  AuthenticatedPurchasesItemsRoute: typeof AuthenticatedPurchasesItemsRoute
  AuthenticatedPurchasesPurchaseOrdersRoute: typeof AuthenticatedPurchasesPurchaseOrdersRouteWithChildren
  AuthenticatedPurchasesUnitTypesRoute: typeof AuthenticatedPurchasesUnitTypesRoute
  AuthenticatedPurchasesVendorsRoute: typeof AuthenticatedPurchasesVendorsRoute
  AuthenticatedAccountsReportsIdRoute: typeof AuthenticatedAccountsReportsIdRoute
  AuthenticatedAccountsReportsNewRoute: typeof AuthenticatedAccountsReportsNewRoute
  AuthenticatedPurchasesGrnsGrnIdRoute: typeof AuthenticatedPurchasesGrnsGrnIdRoute
  AuthenticatedPurchasesGrnsNewRoute: typeof AuthenticatedPurchasesGrnsNewRoute
  AuthenticatedAccountsReportsIndexRoute: typeof AuthenticatedAccountsReportsIndexRoute
  AuthenticatedPurchasesGrnsIndexRoute: typeof AuthenticatedPurchasesGrnsIndexRoute
  AuthenticatedAccountsReportsEditIdRoute: typeof AuthenticatedAccountsReportsEditIdRoute
  AuthenticatedPurchasesGrnsGrnIdEditRoute: typeof AuthenticatedPurchasesGrnsGrnIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCommunicationRoute: AuthenticatedCommunicationRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccountsConsultantChargesRoute:
    AuthenticatedAccountsConsultantChargesRoute,
  AuthenticatedAccountsServiceChargesRoute:
    AuthenticatedAccountsServiceChargesRoute,
  AuthenticatedAdminHospitalRoute: AuthenticatedAdminHospitalRoute,
  AuthenticatedAdminLocalizationRoute: AuthenticatedAdminLocalizationRoute,
  AuthenticatedAdminPayrollRoute: AuthenticatedAdminPayrollRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedClinicalImmunizationRoute:
    AuthenticatedClinicalImmunizationRoute,
  AuthenticatedHrAddStaffRoute: AuthenticatedHrAddStaffRoute,
  AuthenticatedHrAttendanceRoute: AuthenticatedHrAttendanceRoute,
  AuthenticatedHrLeavesRoute: AuthenticatedHrLeavesRoute,
  AuthenticatedHrOffDayRequestsRoute: AuthenticatedHrOffDayRequestsRoute,
  AuthenticatedHrPayrollRoute: AuthenticatedHrPayrollRoute,
  AuthenticatedHrReviewLeaveRoute: AuthenticatedHrReviewLeaveRoute,
  AuthenticatedHrRosterRoute: AuthenticatedHrRosterRoute,
  AuthenticatedHrStaffListRoute: AuthenticatedHrStaffListRoute,
  AuthenticatedHrViewPayslipRoute: AuthenticatedHrViewPayslipRoute,
  AuthenticatedHrViewStaffRoute: AuthenticatedHrViewStaffRoute,
  AuthenticatedMastersBanksRoute: AuthenticatedMastersBanksRoute,
  AuthenticatedMastersDepartmentsRoute: AuthenticatedMastersDepartmentsRoute,
  AuthenticatedMastersLeaveTypesRoute: AuthenticatedMastersLeaveTypesRoute,
  AuthenticatedMastersManagementApproversRoute:
    AuthenticatedMastersManagementApproversRoute,
  AuthenticatedMastersNursingSupersRoute:
    AuthenticatedMastersNursingSupersRoute,
  AuthenticatedMastersRolesRoute: AuthenticatedMastersRolesRoute,
  AuthenticatedMastersSalaryTemplatesRoute:
    AuthenticatedMastersSalaryTemplatesRoute,
  AuthenticatedMastersShiftsRoute: AuthenticatedMastersShiftsRoute,
  AuthenticatedPurchasesBillsRoute: AuthenticatedPurchasesBillsRoute,
  AuthenticatedPurchasesItemTypesRoute: AuthenticatedPurchasesItemTypesRoute,
  AuthenticatedPurchasesItemsRoute: AuthenticatedPurchasesItemsRoute,
  AuthenticatedPurchasesPurchaseOrdersRoute:
    AuthenticatedPurchasesPurchaseOrdersRouteWithChildren,
  AuthenticatedPurchasesUnitTypesRoute: AuthenticatedPurchasesUnitTypesRoute,
  AuthenticatedPurchasesVendorsRoute: AuthenticatedPurchasesVendorsRoute,
  AuthenticatedAccountsReportsIdRoute: AuthenticatedAccountsReportsIdRoute,
  AuthenticatedAccountsReportsNewRoute: AuthenticatedAccountsReportsNewRoute,
  AuthenticatedPurchasesGrnsGrnIdRoute: AuthenticatedPurchasesGrnsGrnIdRoute,
  AuthenticatedPurchasesGrnsNewRoute: AuthenticatedPurchasesGrnsNewRoute,
  AuthenticatedAccountsReportsIndexRoute:
    AuthenticatedAccountsReportsIndexRoute,
  AuthenticatedPurchasesGrnsIndexRoute: AuthenticatedPurchasesGrnsIndexRoute,
  AuthenticatedAccountsReportsEditIdRoute:
    AuthenticatedAccountsReportsEditIdRoute,
  AuthenticatedPurchasesGrnsGrnIdEditRoute:
    AuthenticatedPurchasesGrnsGrnIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  SharedReportTokenRoute: SharedReportTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
