/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedCommunicationRouteImport } from './routes/_authenticated/communication'
import { Route as AuthenticatedMastersShiftsRouteImport } from './routes/_authenticated/masters/shifts'
import { Route as AuthenticatedMastersSalaryTemplatesRouteImport } from './routes/_authenticated/masters/salary-templates'
import { Route as AuthenticatedMastersRolesRouteImport } from './routes/_authenticated/masters/roles'
import { Route as AuthenticatedMastersLeaveTypesRouteImport } from './routes/_authenticated/masters/leave-types'
import { Route as AuthenticatedMastersDepartmentsRouteImport } from './routes/_authenticated/masters/departments'
import { Route as AuthenticatedMastersBanksRouteImport } from './routes/_authenticated/masters/banks'
import { Route as AuthenticatedHrViewStaffRouteImport } from './routes/_authenticated/hr/view-staff'
import { Route as AuthenticatedHrViewPayslipRouteImport } from './routes/_authenticated/hr/view-payslip'
import { Route as AuthenticatedHrStaffListRouteImport } from './routes/_authenticated/hr/staff-list'
import { Route as AuthenticatedHrRosterRouteImport } from './routes/_authenticated/hr/roster'
import { Route as AuthenticatedHrReviewLeaveRouteImport } from './routes/_authenticated/hr/review-leave'
import { Route as AuthenticatedHrPayrollRouteImport } from './routes/_authenticated/hr/payroll'
import { Route as AuthenticatedHrLeavesRouteImport } from './routes/_authenticated/hr/leaves'
import { Route as AuthenticatedHrAttendanceRouteImport } from './routes/_authenticated/hr/attendance'
import { Route as AuthenticatedHrAddStaffRouteImport } from './routes/_authenticated/hr/add-staff'
import { Route as AuthenticatedClinicalImmunizationRouteImport } from './routes/_authenticated/clinical/immunization'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminPayrollRouteImport } from './routes/_authenticated/admin/payroll'
import { Route as AuthenticatedAdminLocalizationRouteImport } from './routes/_authenticated/admin/localization'
import { Route as AuthenticatedAdminHospitalRouteImport } from './routes/_authenticated/admin/hospital'
import { Route as AuthenticatedAccountsServiceChargesRouteImport } from './routes/_authenticated/accounts/service-charges'
import { Route as AuthenticatedAccountsConsultantChargesRouteImport } from './routes/_authenticated/accounts/consultant-charges'
import { Route as AuthenticatedAccountsReportsIndexRouteImport } from './routes/_authenticated/accounts/reports/index'
import { Route as AuthenticatedAccountsReportsNewRouteImport } from './routes/_authenticated/accounts/reports/new'
import { Route as AuthenticatedAccountsReportsIdRouteImport } from './routes/_authenticated/accounts/reports/$id'
import { Route as AuthenticatedAccountsReportsEditIdRouteImport } from './routes/_authenticated/accounts/reports/edit.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunicationRoute =
  AuthenticatedCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersShiftsRoute =
  AuthenticatedMastersShiftsRouteImport.update({
    id: '/masters/shifts',
    path: '/masters/shifts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersSalaryTemplatesRoute =
  AuthenticatedMastersSalaryTemplatesRouteImport.update({
    id: '/masters/salary-templates',
    path: '/masters/salary-templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersRolesRoute =
  AuthenticatedMastersRolesRouteImport.update({
    id: '/masters/roles',
    path: '/masters/roles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersLeaveTypesRoute =
  AuthenticatedMastersLeaveTypesRouteImport.update({
    id: '/masters/leave-types',
    path: '/masters/leave-types',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersDepartmentsRoute =
  AuthenticatedMastersDepartmentsRouteImport.update({
    id: '/masters/departments',
    path: '/masters/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMastersBanksRoute =
  AuthenticatedMastersBanksRouteImport.update({
    id: '/masters/banks',
    path: '/masters/banks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrViewStaffRoute =
  AuthenticatedHrViewStaffRouteImport.update({
    id: '/hr/view-staff',
    path: '/hr/view-staff',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrViewPayslipRoute =
  AuthenticatedHrViewPayslipRouteImport.update({
    id: '/hr/view-payslip',
    path: '/hr/view-payslip',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrStaffListRoute =
  AuthenticatedHrStaffListRouteImport.update({
    id: '/hr/staff-list',
    path: '/hr/staff-list',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrRosterRoute = AuthenticatedHrRosterRouteImport.update({
  id: '/hr/roster',
  path: '/hr/roster',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrReviewLeaveRoute =
  AuthenticatedHrReviewLeaveRouteImport.update({
    id: '/hr/review-leave',
    path: '/hr/review-leave',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrPayrollRoute = AuthenticatedHrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrLeavesRoute = AuthenticatedHrLeavesRouteImport.update({
  id: '/hr/leaves',
  path: '/hr/leaves',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrAttendanceRoute =
  AuthenticatedHrAttendanceRouteImport.update({
    id: '/hr/attendance',
    path: '/hr/attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrAddStaffRoute = AuthenticatedHrAddStaffRouteImport.update({
  id: '/hr/add-staff',
  path: '/hr/add-staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClinicalImmunizationRoute =
  AuthenticatedClinicalImmunizationRouteImport.update({
    id: '/clinical/immunization',
    path: '/clinical/immunization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPayrollRoute =
  AuthenticatedAdminPayrollRouteImport.update({
    id: '/admin/payroll',
    path: '/admin/payroll',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLocalizationRoute =
  AuthenticatedAdminLocalizationRouteImport.update({
    id: '/admin/localization',
    path: '/admin/localization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminHospitalRoute =
  AuthenticatedAdminHospitalRouteImport.update({
    id: '/admin/hospital',
    path: '/admin/hospital',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsServiceChargesRoute =
  AuthenticatedAccountsServiceChargesRouteImport.update({
    id: '/accounts/service-charges',
    path: '/accounts/service-charges',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsConsultantChargesRoute =
  AuthenticatedAccountsConsultantChargesRouteImport.update({
    id: '/accounts/consultant-charges',
    path: '/accounts/consultant-charges',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsReportsIndexRoute =
  AuthenticatedAccountsReportsIndexRouteImport.update({
    id: '/accounts/reports/',
    path: '/accounts/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsReportsNewRoute =
  AuthenticatedAccountsReportsNewRouteImport.update({
    id: '/accounts/reports/new',
    path: '/accounts/reports/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsReportsIdRoute =
  AuthenticatedAccountsReportsIdRouteImport.update({
    id: '/accounts/reports/$id',
    path: '/accounts/reports/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsReportsEditIdRoute =
  AuthenticatedAccountsReportsEditIdRouteImport.update({
    id: '/accounts/reports/edit/$id',
    path: '/accounts/reports/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/accounts/consultant-charges': typeof AuthenticatedAccountsConsultantChargesRoute
  '/accounts/service-charges': typeof AuthenticatedAccountsServiceChargesRoute
  '/admin/hospital': typeof AuthenticatedAdminHospitalRoute
  '/admin/localization': typeof AuthenticatedAdminLocalizationRoute
  '/admin/payroll': typeof AuthenticatedAdminPayrollRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/clinical/immunization': typeof AuthenticatedClinicalImmunizationRoute
  '/hr/add-staff': typeof AuthenticatedHrAddStaffRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/leaves': typeof AuthenticatedHrLeavesRoute
  '/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/hr/review-leave': typeof AuthenticatedHrReviewLeaveRoute
  '/hr/roster': typeof AuthenticatedHrRosterRoute
  '/hr/staff-list': typeof AuthenticatedHrStaffListRoute
  '/hr/view-payslip': typeof AuthenticatedHrViewPayslipRoute
  '/hr/view-staff': typeof AuthenticatedHrViewStaffRoute
  '/masters/banks': typeof AuthenticatedMastersBanksRoute
  '/masters/departments': typeof AuthenticatedMastersDepartmentsRoute
  '/masters/leave-types': typeof AuthenticatedMastersLeaveTypesRoute
  '/masters/roles': typeof AuthenticatedMastersRolesRoute
  '/masters/salary-templates': typeof AuthenticatedMastersSalaryTemplatesRoute
  '/masters/shifts': typeof AuthenticatedMastersShiftsRoute
  '/accounts/reports/$id': typeof AuthenticatedAccountsReportsIdRoute
  '/accounts/reports/new': typeof AuthenticatedAccountsReportsNewRoute
  '/accounts/reports/': typeof AuthenticatedAccountsReportsIndexRoute
  '/accounts/reports/edit/$id': typeof AuthenticatedAccountsReportsEditIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/accounts/consultant-charges': typeof AuthenticatedAccountsConsultantChargesRoute
  '/accounts/service-charges': typeof AuthenticatedAccountsServiceChargesRoute
  '/admin/hospital': typeof AuthenticatedAdminHospitalRoute
  '/admin/localization': typeof AuthenticatedAdminLocalizationRoute
  '/admin/payroll': typeof AuthenticatedAdminPayrollRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/clinical/immunization': typeof AuthenticatedClinicalImmunizationRoute
  '/hr/add-staff': typeof AuthenticatedHrAddStaffRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/leaves': typeof AuthenticatedHrLeavesRoute
  '/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/hr/review-leave': typeof AuthenticatedHrReviewLeaveRoute
  '/hr/roster': typeof AuthenticatedHrRosterRoute
  '/hr/staff-list': typeof AuthenticatedHrStaffListRoute
  '/hr/view-payslip': typeof AuthenticatedHrViewPayslipRoute
  '/hr/view-staff': typeof AuthenticatedHrViewStaffRoute
  '/masters/banks': typeof AuthenticatedMastersBanksRoute
  '/masters/departments': typeof AuthenticatedMastersDepartmentsRoute
  '/masters/leave-types': typeof AuthenticatedMastersLeaveTypesRoute
  '/masters/roles': typeof AuthenticatedMastersRolesRoute
  '/masters/salary-templates': typeof AuthenticatedMastersSalaryTemplatesRoute
  '/masters/shifts': typeof AuthenticatedMastersShiftsRoute
  '/accounts/reports/$id': typeof AuthenticatedAccountsReportsIdRoute
  '/accounts/reports/new': typeof AuthenticatedAccountsReportsNewRoute
  '/accounts/reports': typeof AuthenticatedAccountsReportsIndexRoute
  '/accounts/reports/edit/$id': typeof AuthenticatedAccountsReportsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/communication': typeof AuthenticatedCommunicationRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/accounts/consultant-charges': typeof AuthenticatedAccountsConsultantChargesRoute
  '/_authenticated/accounts/service-charges': typeof AuthenticatedAccountsServiceChargesRoute
  '/_authenticated/admin/hospital': typeof AuthenticatedAdminHospitalRoute
  '/_authenticated/admin/localization': typeof AuthenticatedAdminLocalizationRoute
  '/_authenticated/admin/payroll': typeof AuthenticatedAdminPayrollRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/clinical/immunization': typeof AuthenticatedClinicalImmunizationRoute
  '/_authenticated/hr/add-staff': typeof AuthenticatedHrAddStaffRoute
  '/_authenticated/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/_authenticated/hr/leaves': typeof AuthenticatedHrLeavesRoute
  '/_authenticated/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/_authenticated/hr/review-leave': typeof AuthenticatedHrReviewLeaveRoute
  '/_authenticated/hr/roster': typeof AuthenticatedHrRosterRoute
  '/_authenticated/hr/staff-list': typeof AuthenticatedHrStaffListRoute
  '/_authenticated/hr/view-payslip': typeof AuthenticatedHrViewPayslipRoute
  '/_authenticated/hr/view-staff': typeof AuthenticatedHrViewStaffRoute
  '/_authenticated/masters/banks': typeof AuthenticatedMastersBanksRoute
  '/_authenticated/masters/departments': typeof AuthenticatedMastersDepartmentsRoute
  '/_authenticated/masters/leave-types': typeof AuthenticatedMastersLeaveTypesRoute
  '/_authenticated/masters/roles': typeof AuthenticatedMastersRolesRoute
  '/_authenticated/masters/salary-templates': typeof AuthenticatedMastersSalaryTemplatesRoute
  '/_authenticated/masters/shifts': typeof AuthenticatedMastersShiftsRoute
  '/_authenticated/accounts/reports/$id': typeof AuthenticatedAccountsReportsIdRoute
  '/_authenticated/accounts/reports/new': typeof AuthenticatedAccountsReportsNewRoute
  '/_authenticated/accounts/reports/': typeof AuthenticatedAccountsReportsIndexRoute
  '/_authenticated/accounts/reports/edit/$id': typeof AuthenticatedAccountsReportsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/communication'
    | '/settings'
    | '/accounts/consultant-charges'
    | '/accounts/service-charges'
    | '/admin/hospital'
    | '/admin/localization'
    | '/admin/payroll'
    | '/admin/users'
    | '/clinical/immunization'
    | '/hr/add-staff'
    | '/hr/attendance'
    | '/hr/leaves'
    | '/hr/payroll'
    | '/hr/review-leave'
    | '/hr/roster'
    | '/hr/staff-list'
    | '/hr/view-payslip'
    | '/hr/view-staff'
    | '/masters/banks'
    | '/masters/departments'
    | '/masters/leave-types'
    | '/masters/roles'
    | '/masters/salary-templates'
    | '/masters/shifts'
    | '/accounts/reports/$id'
    | '/accounts/reports/new'
    | '/accounts/reports/'
    | '/accounts/reports/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/communication'
    | '/settings'
    | '/'
    | '/accounts/consultant-charges'
    | '/accounts/service-charges'
    | '/admin/hospital'
    | '/admin/localization'
    | '/admin/payroll'
    | '/admin/users'
    | '/clinical/immunization'
    | '/hr/add-staff'
    | '/hr/attendance'
    | '/hr/leaves'
    | '/hr/payroll'
    | '/hr/review-leave'
    | '/hr/roster'
    | '/hr/staff-list'
    | '/hr/view-payslip'
    | '/hr/view-staff'
    | '/masters/banks'
    | '/masters/departments'
    | '/masters/leave-types'
    | '/masters/roles'
    | '/masters/salary-templates'
    | '/masters/shifts'
    | '/accounts/reports/$id'
    | '/accounts/reports/new'
    | '/accounts/reports'
    | '/accounts/reports/edit/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/communication'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/accounts/consultant-charges'
    | '/_authenticated/accounts/service-charges'
    | '/_authenticated/admin/hospital'
    | '/_authenticated/admin/localization'
    | '/_authenticated/admin/payroll'
    | '/_authenticated/admin/users'
    | '/_authenticated/clinical/immunization'
    | '/_authenticated/hr/add-staff'
    | '/_authenticated/hr/attendance'
    | '/_authenticated/hr/leaves'
    | '/_authenticated/hr/payroll'
    | '/_authenticated/hr/review-leave'
    | '/_authenticated/hr/roster'
    | '/_authenticated/hr/staff-list'
    | '/_authenticated/hr/view-payslip'
    | '/_authenticated/hr/view-staff'
    | '/_authenticated/masters/banks'
    | '/_authenticated/masters/departments'
    | '/_authenticated/masters/leave-types'
    | '/_authenticated/masters/roles'
    | '/_authenticated/masters/salary-templates'
    | '/_authenticated/masters/shifts'
    | '/_authenticated/accounts/reports/$id'
    | '/_authenticated/accounts/reports/new'
    | '/_authenticated/accounts/reports/'
    | '/_authenticated/accounts/reports/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/communication': {
      id: '/_authenticated/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof AuthenticatedCommunicationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/shifts': {
      id: '/_authenticated/masters/shifts'
      path: '/masters/shifts'
      fullPath: '/masters/shifts'
      preLoaderRoute: typeof AuthenticatedMastersShiftsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/salary-templates': {
      id: '/_authenticated/masters/salary-templates'
      path: '/masters/salary-templates'
      fullPath: '/masters/salary-templates'
      preLoaderRoute: typeof AuthenticatedMastersSalaryTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/roles': {
      id: '/_authenticated/masters/roles'
      path: '/masters/roles'
      fullPath: '/masters/roles'
      preLoaderRoute: typeof AuthenticatedMastersRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/leave-types': {
      id: '/_authenticated/masters/leave-types'
      path: '/masters/leave-types'
      fullPath: '/masters/leave-types'
      preLoaderRoute: typeof AuthenticatedMastersLeaveTypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/departments': {
      id: '/_authenticated/masters/departments'
      path: '/masters/departments'
      fullPath: '/masters/departments'
      preLoaderRoute: typeof AuthenticatedMastersDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters/banks': {
      id: '/_authenticated/masters/banks'
      path: '/masters/banks'
      fullPath: '/masters/banks'
      preLoaderRoute: typeof AuthenticatedMastersBanksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/view-staff': {
      id: '/_authenticated/hr/view-staff'
      path: '/hr/view-staff'
      fullPath: '/hr/view-staff'
      preLoaderRoute: typeof AuthenticatedHrViewStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/view-payslip': {
      id: '/_authenticated/hr/view-payslip'
      path: '/hr/view-payslip'
      fullPath: '/hr/view-payslip'
      preLoaderRoute: typeof AuthenticatedHrViewPayslipRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/staff-list': {
      id: '/_authenticated/hr/staff-list'
      path: '/hr/staff-list'
      fullPath: '/hr/staff-list'
      preLoaderRoute: typeof AuthenticatedHrStaffListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/roster': {
      id: '/_authenticated/hr/roster'
      path: '/hr/roster'
      fullPath: '/hr/roster'
      preLoaderRoute: typeof AuthenticatedHrRosterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/review-leave': {
      id: '/_authenticated/hr/review-leave'
      path: '/hr/review-leave'
      fullPath: '/hr/review-leave'
      preLoaderRoute: typeof AuthenticatedHrReviewLeaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/payroll': {
      id: '/_authenticated/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof AuthenticatedHrPayrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/leaves': {
      id: '/_authenticated/hr/leaves'
      path: '/hr/leaves'
      fullPath: '/hr/leaves'
      preLoaderRoute: typeof AuthenticatedHrLeavesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/attendance': {
      id: '/_authenticated/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof AuthenticatedHrAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/add-staff': {
      id: '/_authenticated/hr/add-staff'
      path: '/hr/add-staff'
      fullPath: '/hr/add-staff'
      preLoaderRoute: typeof AuthenticatedHrAddStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clinical/immunization': {
      id: '/_authenticated/clinical/immunization'
      path: '/clinical/immunization'
      fullPath: '/clinical/immunization'
      preLoaderRoute: typeof AuthenticatedClinicalImmunizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/payroll': {
      id: '/_authenticated/admin/payroll'
      path: '/admin/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AuthenticatedAdminPayrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/localization': {
      id: '/_authenticated/admin/localization'
      path: '/admin/localization'
      fullPath: '/admin/localization'
      preLoaderRoute: typeof AuthenticatedAdminLocalizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/hospital': {
      id: '/_authenticated/admin/hospital'
      path: '/admin/hospital'
      fullPath: '/admin/hospital'
      preLoaderRoute: typeof AuthenticatedAdminHospitalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/service-charges': {
      id: '/_authenticated/accounts/service-charges'
      path: '/accounts/service-charges'
      fullPath: '/accounts/service-charges'
      preLoaderRoute: typeof AuthenticatedAccountsServiceChargesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/consultant-charges': {
      id: '/_authenticated/accounts/consultant-charges'
      path: '/accounts/consultant-charges'
      fullPath: '/accounts/consultant-charges'
      preLoaderRoute: typeof AuthenticatedAccountsConsultantChargesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/reports/': {
      id: '/_authenticated/accounts/reports/'
      path: '/accounts/reports'
      fullPath: '/accounts/reports/'
      preLoaderRoute: typeof AuthenticatedAccountsReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/reports/new': {
      id: '/_authenticated/accounts/reports/new'
      path: '/accounts/reports/new'
      fullPath: '/accounts/reports/new'
      preLoaderRoute: typeof AuthenticatedAccountsReportsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/reports/$id': {
      id: '/_authenticated/accounts/reports/$id'
      path: '/accounts/reports/$id'
      fullPath: '/accounts/reports/$id'
      preLoaderRoute: typeof AuthenticatedAccountsReportsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/reports/edit/$id': {
      id: '/_authenticated/accounts/reports/edit/$id'
      path: '/accounts/reports/edit/$id'
      fullPath: '/accounts/reports/edit/$id'
      preLoaderRoute: typeof AuthenticatedAccountsReportsEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCommunicationRoute: typeof AuthenticatedCommunicationRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccountsConsultantChargesRoute: typeof AuthenticatedAccountsConsultantChargesRoute
  AuthenticatedAccountsServiceChargesRoute: typeof AuthenticatedAccountsServiceChargesRoute
  AuthenticatedAdminHospitalRoute: typeof AuthenticatedAdminHospitalRoute
  AuthenticatedAdminLocalizationRoute: typeof AuthenticatedAdminLocalizationRoute
  AuthenticatedAdminPayrollRoute: typeof AuthenticatedAdminPayrollRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedClinicalImmunizationRoute: typeof AuthenticatedClinicalImmunizationRoute
  AuthenticatedHrAddStaffRoute: typeof AuthenticatedHrAddStaffRoute
  AuthenticatedHrAttendanceRoute: typeof AuthenticatedHrAttendanceRoute
  AuthenticatedHrLeavesRoute: typeof AuthenticatedHrLeavesRoute
  AuthenticatedHrPayrollRoute: typeof AuthenticatedHrPayrollRoute
  AuthenticatedHrReviewLeaveRoute: typeof AuthenticatedHrReviewLeaveRoute
  AuthenticatedHrRosterRoute: typeof AuthenticatedHrRosterRoute
  AuthenticatedHrStaffListRoute: typeof AuthenticatedHrStaffListRoute
  AuthenticatedHrViewPayslipRoute: typeof AuthenticatedHrViewPayslipRoute
  AuthenticatedHrViewStaffRoute: typeof AuthenticatedHrViewStaffRoute
  AuthenticatedMastersBanksRoute: typeof AuthenticatedMastersBanksRoute
  AuthenticatedMastersDepartmentsRoute: typeof AuthenticatedMastersDepartmentsRoute
  AuthenticatedMastersLeaveTypesRoute: typeof AuthenticatedMastersLeaveTypesRoute
  AuthenticatedMastersRolesRoute: typeof AuthenticatedMastersRolesRoute
  AuthenticatedMastersSalaryTemplatesRoute: typeof AuthenticatedMastersSalaryTemplatesRoute
  AuthenticatedMastersShiftsRoute: typeof AuthenticatedMastersShiftsRoute
  AuthenticatedAccountsReportsIdRoute: typeof AuthenticatedAccountsReportsIdRoute
  AuthenticatedAccountsReportsNewRoute: typeof AuthenticatedAccountsReportsNewRoute
  AuthenticatedAccountsReportsIndexRoute: typeof AuthenticatedAccountsReportsIndexRoute
  AuthenticatedAccountsReportsEditIdRoute: typeof AuthenticatedAccountsReportsEditIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCommunicationRoute: AuthenticatedCommunicationRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccountsConsultantChargesRoute:
    AuthenticatedAccountsConsultantChargesRoute,
  AuthenticatedAccountsServiceChargesRoute:
    AuthenticatedAccountsServiceChargesRoute,
  AuthenticatedAdminHospitalRoute: AuthenticatedAdminHospitalRoute,
  AuthenticatedAdminLocalizationRoute: AuthenticatedAdminLocalizationRoute,
  AuthenticatedAdminPayrollRoute: AuthenticatedAdminPayrollRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedClinicalImmunizationRoute:
    AuthenticatedClinicalImmunizationRoute,
  AuthenticatedHrAddStaffRoute: AuthenticatedHrAddStaffRoute,
  AuthenticatedHrAttendanceRoute: AuthenticatedHrAttendanceRoute,
  AuthenticatedHrLeavesRoute: AuthenticatedHrLeavesRoute,
  AuthenticatedHrPayrollRoute: AuthenticatedHrPayrollRoute,
  AuthenticatedHrReviewLeaveRoute: AuthenticatedHrReviewLeaveRoute,
  AuthenticatedHrRosterRoute: AuthenticatedHrRosterRoute,
  AuthenticatedHrStaffListRoute: AuthenticatedHrStaffListRoute,
  AuthenticatedHrViewPayslipRoute: AuthenticatedHrViewPayslipRoute,
  AuthenticatedHrViewStaffRoute: AuthenticatedHrViewStaffRoute,
  AuthenticatedMastersBanksRoute: AuthenticatedMastersBanksRoute,
  AuthenticatedMastersDepartmentsRoute: AuthenticatedMastersDepartmentsRoute,
  AuthenticatedMastersLeaveTypesRoute: AuthenticatedMastersLeaveTypesRoute,
  AuthenticatedMastersRolesRoute: AuthenticatedMastersRolesRoute,
  AuthenticatedMastersSalaryTemplatesRoute:
    AuthenticatedMastersSalaryTemplatesRoute,
  AuthenticatedMastersShiftsRoute: AuthenticatedMastersShiftsRoute,
  AuthenticatedAccountsReportsIdRoute: AuthenticatedAccountsReportsIdRoute,
  AuthenticatedAccountsReportsNewRoute: AuthenticatedAccountsReportsNewRoute,
  AuthenticatedAccountsReportsIndexRoute:
    AuthenticatedAccountsReportsIndexRoute,
  AuthenticatedAccountsReportsEditIdRoute:
    AuthenticatedAccountsReportsEditIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
