export type StaffRow = {
  /** Stable logical identity — never changes across versions. */
  staffId: number;
  /** Version number of this record. Increments on every staff detail update. */
  version: number;
  /** True for the latest (current) version of this staff member. */
  active: boolean;
  employeeCode: string;
  name: string;
  role: string;
  status: string;
  aadhar: string;
  phone: string;
  pan: string;
  departmentId?: number | null;
  departmentName?: string | null;
  email?: string | null;
  basicSalary?: number | null;
  hra?: number | null;
  conveyance?: number | null;
  skillAllowance?: number | null;
  special?: number | null;
  epf?: number | null;
  esi?: number | null;
  professionalTax?: number | null;
  deductTds?: boolean | null;
  tdsPercent?: number | null;
  tds?: number | null;
  securityDepositTotal?: number | null;
  securityDeposit?: number | null;
  securityDepositStartMonth?: string | null;
  otherDeductions?: number | null;
  lateAttendance?: number | null;
  salary?: number | null;
  userId?: string | null;
  isExecutive?: boolean;
  effectiveDate?: string | null;
  employmentType?: string | null;
  permanentConfirmationDate?: string | null;
  employmentStartDate?: string | null;
  employmentEndDate?: string | null;
  supervisorLevel1Id?: number | null;
  supervisorLevel2Id?: number | null;
  createdAt: string;
};
export type PatientRow = { id: number; name: string };
export type DepartmentRow = {
  id: number;
  name: string;
  floor?: string;
  head?: string;
  active?: boolean;
  headStaffId?: number | null;
  headName?: string | null;
  subheadStaffId?: number | null;
  subheadName?: string | null;
};
export type ScheduleRow = { id: number; token: string; patient: string; doctor: string; department: string; status: string };
export type InventoryRow = { id: number; sku: string; name: string; category: string; quantity: number; reorderLevel: number; location: string };
export type MedicineRow = { id: number; sku: string; name: string; genericName: string; stock: number; reorderLevel: number; price: number };
export type PrescriptionRow = { id: number; patient: string; doctor: string; status: string };
export type LeaveRow = {
  id: number;
  requestNo: string;
  employeeCode: string;
  staffName: string;
  leaveType: string;
  startDate: string;
  endDate: string;
  reason: string;
  status: string;
  reviewerNote?: string | null;
  dateRange?: string;
  departmentName?: string | null;
  staffId?: number;
  supervisorLevel1Id?: number | null;
  supervisorLevel2Id?: number | null;
  approverIds?: string | null;
  supportingDocument?: string | null;
};

export type LeaveDetailRow = {
  id: number;
  requestNo: string;
  leaveType: string;
  startDate: string;
  endDate: string;
  reason: string;
  status: string;
  reviewerNote?: string | null;
  reviewedAt?: string | null;
  createdAt: string;
  staffId: number;
  employeeCode: string;
  staffName: string;
  staffEmail: string;
  staffPhone: string;
  staffRole: string;
  departmentId?: number | null;
  departmentName?: string | null;
  supervisorLevel1Id?: number | null;
  supervisorLevel1Name?: string | null;
  supervisorLevel2Id?: number | null;
  supervisorLevel2Name?: string | null;
  headStaffId?: number | null;
  subheadStaffId?: number | null;
  forwardedToStaffId?: number | null;
  forwardedToStaffName?: string | null;
  approverIds?: string | null;
  supportingDocument?: string | null;
};
export type RoleTypeRow = { id: number; name: string; active: boolean };
export type LeaveTypeRow = { id: number; name: string; maxDays: number; active: boolean; payable: boolean; paymentRate: number };
export type ShiftRow = { id: number; name: string; code: string; startTime: string; endTime: string; active: boolean; isOffDay: boolean; sortOrder: number };
export type RosterRow = {
  id: number;
  staffId: number;
  staffName: string;
  departmentId: number;
  departmentName: string;
  shiftId: number;
  shift: string;
  isOffDay: boolean;
  /** Single calendar date (YYYY-MM-DD). One row = one day. */
  date: string;
  notes?: string | null;
  createdAt: string;
};
