export type StaffRow = {
  id: number;
  employeeCode: string;
  name: string;
  role: string;
  status: string;
  aadhar: string;
  phone: string;
  pan: string;
  version?: number;
  active?: boolean;
  departmentId?: number | null;
  departmentName?: string | null;
  supervisorLevel1Id?: number | null;
  supervisorLevel1Name?: string | null;
  supervisorLevel2Id?: number | null;
  supervisorLevel2Name?: string | null;
  email?: string | null;
  basicSalary?: number | null;
  hra?: number | null;
  conveyance?: number | null;
  medical?: number | null;
  special?: number | null;
  epf?: number | null;
  esi?: number | null;
  professionalTax?: number | null;
  otherDeductions?: number | null;
  salary?: number | null;
  createdAt: string;
};
export type PatientRow = { id: number; name: string };
export type DepartmentRow = { id: number; name: string };
export type ScheduleRow = { id: number; token: string; patient: string; doctor: string; department: string; status: string };
export type InventoryRow = { id: number; sku: string; name: string; category: string; quantity: number; reorderLevel: number; location: string };
export type MedicineRow = { id: number; sku: string; name: string; genericName: string; stock: number; reorderLevel: number; price: number };
export type PrescriptionRow = { id: number; patient: string; doctor: string; status: string };
export type LeaveRow = {
  id: number;
  requestNo: string;
  employeeCode: string;
  staffName: string;
  leaveType: string;
  startDate: string;
  endDate: string;
  reason: string;
  status: string;
  reviewerNote?: string | null;
  dateRange?: string;
  staffId?: number;
  supervisorLevel1Id?: number | null;
  supervisorLevel2Id?: number | null;
};

export type LeaveDetailRow = {
  id: number;
  requestNo: string;
  leaveType: string;
  startDate: string;
  endDate: string;
  reason: string;
  status: string;
  reviewerNote?: string | null;
  reviewedAt?: string | null;
  createdAt: string;
  staffId: number;
  employeeCode: string;
  staffName: string;
  staffEmail: string;
  staffPhone: string;
  staffRole: string;
  departmentId?: number | null;
  departmentName?: string | null;
  supervisorLevel1Id?: number | null;
  supervisorLevel1Name?: string | null;
  supervisorLevel2Id?: number | null;
  supervisorLevel2Name?: string | null;
  headStaffId?: number | null;
  subheadStaffId?: number | null;
};
export type RoleTypeRow = { id: number; name: string; active: boolean };
export type LeaveTypeRow = { id: number; name: string; maxDays: number; active: boolean; payable: boolean; paymentRate: number };
export type ShiftRow = { id: number; name: string; code: string; startTime: string; endTime: string; active: boolean; isOffDay: boolean; sortOrder: number };
export type RosterRow = {
  id: number;
  staffId: number;
  staffName: string;
  departmentId: number;
  departmentName: string;
  shiftId: number;
  shift: string;
  isOffDay: boolean;
  startDate: string;
  endDate: string;
  notes?: string | null;
  createdAt: string;
};
